name: "[CI] Continuous Integration"

on:
  pull_request:
    types: [opened, synchronize]

env:
  SUPABASE_URL: ${{secrets.SUPABASE_URL}}
  SUPABASE_PUBLIC_KEY: ${{secrets.SUPABASE_PUBLIC_KEY}}
  SUPABASE_SECRET_KEY: ${{secrets.SUPABASE_SECRET_KEY}}

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: "Debug"
        run: "ls -la"
      - name: "Install dependencies"
        run: "npm ci"
      - name: "Lint project"
        run: "npm run lint"
  test:
    runs-on: ubuntu-latest
    container: cypress/browsers:node16.16.0-chrome107-ff107-edge
    steps:
      - uses: actions/checkout@v3
      - name: "Debug"
        run: "ls -la"
      - name: "Install Dependencies"
        run: "npm ci"
      - name: Run tests with cypress
        run: "npm run test"
