name: "[CD] Continuous Delivery"

on:
  pull_request:
    types: [opened, synchronize]

env:
    VERCEL_ORG_ID: uPTAMwfDLIP8xACgqdobxvOL
    VERCEL_PROJECT_ID: prj_8fIzO9odbl58hXKwqYWsBhjeDFz5

jobs:
   lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: "Debug"
        run: "ls -la"
      - name: "Install dependencies"
        run: "npm ci"
      - name: "Deploy"
        run: "npx vercel --prod token=${{ secrets.VERCEL_TOKEN }}"
